export const projects = [
  {
    slug: "bina-hydropower",
    name: "Bina Hydropower Project",
    location: "Bina River, Narmadapuram District, MP",
    district: "Narmadapuram",
    capacity: "—",
    tech: ["Hydro"],
    status: "Installation Phase" as const,
    statusTone: "progress" as const,
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    excerpt: "Run-of-river hydropower development on the Bina River with executed HDA and security deposit completed.",
    steps: ["Project Allotment","HDA Executed","Security Deposit","Land Acquisition","Installation"],
    currentStep: 4,
    facts: { capacity:"To be assessed", technology:"Hydropower (run-of-river)", location:"Bina River, MP", status:"Installation Phase" },
    description:"The Bina Hydropower Project is Thapak Power's flagship hydro development. With the Hydropower Development Agreement (HDA) executed and Security Deposit (SD) submitted, the project is advancing through land acquisition toward installation. Technical assessments and Detailed Project Report (DPR) underpin the development approach.",
  },
  {
    slug: "tamia-solar-wind-hybrid",
    name: "Tamia Solar–Wind Hybrid Project",
    location: "Tamia, Chhindwara District, MP",
    district: "Chhindwara",
    capacity: "50 MW",
    tech: ["Solar","Wind","Hybrid"],
    status: "DPR Completed" as const,
    statusTone: "planned" as const,
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    excerpt: "50 MW solar-wind hybrid integrating complementary generation profiles for higher capacity utilisation.",
    steps: ["Technology Identification","Site Selection","Technical Assessment","DPR Development","Statutory & Development","Engineering & Installation","Testing & Evaluation","Operation"],
    currentStep: 3,
    facts: { capacity:"50 MW", technology:"Solar–Wind Hybrid", location:"Tamia, Chhindwara, MP", status:"DPR Completed" },
    description:"Tamia combines solar and wind resources at a single site to deliver hybrid renewable power with improved generation consistency. The Detailed Project Report (DPR) is complete, establishing technical feasibility and integration strategy for hybrid delivery and future storage coupling.",
  },
  {
    slug: "budhni-solar-thermal",
    name: "Budhni Solar Thermal Project",
    location: "Budhni, Sehore District, MP",
    district: "Sehore",
    capacity: "100 MW + Storage",
    tech: ["Solar Thermal","Storage"],
    status: "Planned" as const,
    statusTone: "planned" as const,
    image: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=800&q=80",
    excerpt: "100 MW solar thermal with integrated thermal storage for dispatchable, controlled power delivery.",
    steps: ["Technology Identification","Site Selection","Technical Assessment","DPR Development","Statutory & Development","Engineering & Installation","Testing & Evaluation","Operation"],
    currentStep: 1,
    facts: { capacity:"100 MW + Thermal Storage", technology:"Solar Thermal + Storage", location:"Budhni, Sehore, MP", status:"Planned" },
    description:"Budhni leverages licensed solar thermal power and storage technology to provide dispatchable renewable generation. Thermal storage enables controlled power delivery beyond daylight hours — a key enabler for grid reliability and round-the-clock renewable supply.",
  },
];

export const focusItems = [
  { title:"Hydropower", desc:"Run-of-river & storage hydro", icon:"hydro" },
  { title:"Solar", desc:"PV & solar thermal systems", icon:"solar" },
  { title:"Wind", desc:"Patent-licensed turbine tech", icon:"wind" },
  { title:"Hybrid", desc:"Solar + Wind integration", icon:"hybrid" },
  { title:"Energy Storage", desc:"Short-time & thermal storage", icon:"storage" },
  { title:"Grid Support", desc:"Fluctuation reduction systems", icon:"grid" },
];

export const whyPoints = [
  { title:"Technology Driven", desc:"Engineering-led development from first principles." },
  { title:"Multi-Technology Approach", desc:"Hydro, solar, wind, hybrid and storage under one platform." },
  { title:"Intellectual Property", desc:"Patented and licensed technologies strengthen every project." },
  { title:"In-House R&D", desc:"Dedicated testing and validation facility." },
  { title:"Project Development Capability", desc:"End-to-end: site to operation & optimisation." },
  { title:"Integrated Energy Approach", desc:"Generation, storage and grid support co-designed." },
];

export const eightSteps = [
  { n:"01", t:"Technology Identification", d:"Select generation & storage tech for site conditions." },
  { n:"02", t:"Site Selection", d:"Resource mapping, terrain and grid proximity analysis." },
  { n:"03", t:"Technical Assessment", d:"Feasibility, hydrology/meteorology, yield modelling." },
  { n:"04", t:"DPR Development", d:"Detailed Project Report with engineering & financial plan." },
  { n:"05", t:"Statutory & Project Development", d:"HDA, SD and regulatory clearances." },
  { n:"06", t:"Engineering & Installation", d:"EPC execution, integration and construction." },
  { n:"07", t:"Testing & Performance Evaluation", d:"Commissioning, measurement and validation." },
  { n:"08", t:"Operation & Technology Improvement", d:"Operations with continuous R&D feedback loop." },
];
